export const ProjectsData = [
    {
        title: "Dumka Calgary",
        link: "https://dumkacalgary.com/",
        image: "/projects/dc-min.png",
        github: "https://github.com/thetechie7/dumka-calgary",
    },
    {
        title: "JumpStarterX (Unreleased)",
        link: "https://jumpstarterx.com/",
        image: "/projects/jsx-min.png",
        github: "https://github.com/thetechie7/jumpstarterx",
    },
    {
        title: "Reactive Shots NFT Marketplace",
        link: "https://nft.reactiveshots.com/",
        image: "/projects/rsnft-min.png",
        github: "https://github.com/thetechie7/rs-nft",
    },
    {
        title: "Pista Express",
        link: "https://pistaexpress.com/",
        image: "/projects/pe-min.png",
        github: "https://github.com/thetechie7/pistaexpress",
    },
    {
        title: "Reactive Shots",
        link: "https://reactiveshots.com/",
        image: "/projects/rs-min.png",
        github: "https://github.com/thetechie7/reactive-shots",
    },
    {
        title: "Pista House Irving",
        link: "https://pistahouseirving.com/",
        image: "/projects/phi-min.png",
        github: "https://github.com/thetechie7/pistahouseirving",
    },
    {
        title: "Legal Dove",
        link: "https://legaldove.geethg.com/",
        image: "/projects/ld-min.png",
        github: "https://github.com/thetechie7/legaldove",
    },
    {
        title: "Infinity Loops Bot",
        link: "https://github.com/thetechie7/InfinityLoopsBot",
        image: "/projects/ilb-min.png",
        github: "https://github.com/thetechie7/InfinityLoopsBot",
    },
    {
        title: "MyPanchang",
        link: "https://mypanchang.app/",
        image: "/projects/myp-min.png",
        github: "",
        apple: "https://apps.apple.com/us/app/mypanchang/id1567820028",
    },
    {
        title: "HS Connect",
        link: "https://hsc.geethg.com/",
        image: "/projects/hsc-min.png",
        github: "https://github.com/HighSchoolConnect/hs-connect-react",
    },
    {
        title: "Peer Assisted Learning",
        link: "https://pal.geethg.com/",
        image: "/projects/pal-min.png",
        github: "https://github.com/thetechie7/pal-club-website",
    },
    {
        title: "Coppell For Youth",
        link: "https://coppellforyouth.vercel.app/",
        image: "/projects/cfy-min.png",
        github: "https://github.com/thetechie7/coppellforyouth",
    },
]
